### ISSUE TITLE
Latest version of ip-address brokens the library

### ISSUE THREAD

**Issue by arcifius** [jas-/node-libnmap#38]
The latest version of ip-address broke the library.

The **v6.Address** is now undefined. It should be **require('ip-address').Address6**

**Comment by jas-** [comment]
And the latest version of this library supports up to 4.2.0 of the ip-address dependency. How did you install this package?

The only supported method is 'npm install'.

**Comment by jas-** [comment]
@arcifius This should be resolved as of the `v0.2.31` branch installed from `npm install --save libnmap`. Can you confirm?

**Comment by stemmlerjs** [comment]
I just installed the v0.2.31 branch by doing npm install --save libnmap and I still have this problem.

`netmask = new v6.Address(netmask).subnet.substring(1);
                  ^

TypeError: v6.Address is not a function`

**Comment by jas-** [comment]
@arcifius @stemmlerjs This should be resolved with the `v0.2.32` release. Thanks for reporting this.

**Comment by stemmlerjs** [comment]
**@jas-** Good stuff, works for me now with the v0.2.32 release. Thanks for putting out this tool.
